language: cpp
sudo: required
compiler: gcc
cache: ccache

env:
  - ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-

addons:
  apt: 
    packages: 
    - gcc-arm-linux-gnueabihf 
    - g++-arm-linux-gnueabihf 
    - debootstrap 
    - qemu-user-static 
    - binfmt-support 
    - sbuild 
    - lzop 
    - wget 
    - ccache

script:
- chmod +x ./build.sh
- ./build.sh

deploy:
  provider: releases
  api_key:
    secure: $GH_TOKEN
  file: "main"
  skip_cleanup: true
  on: 
    branch: master
