language: cpp
compiler: gcc
cache: ccache

env:
  - ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-

addons:
  apt: 
    packages: 
    - gcc-arm-linux-gnueabihf 
    - g++-arm-linux-gnueabihf

before_install:
    - ./chmod +x ./build.sh
script:
    - ./build.sh

deploy:
  provider: releases
  api_key:
    secure: $GH_TOKEN
  file: "main"
  skip_cleanup: true
  on: 
    branch: master
    tags: true
